ERROR - 2021-12-13 02:31:00 --> Error connecting to the database: Connection refused
CRITICAL - 2021-12-13 02:31:00 --> Unable to connect to the database.
Main connection [MySQLi]: Connection refused
#0 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Database/BaseConnection.php(625): CodeIgniter\Database\BaseConnection->initialize()
#1 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/BaseModel.php(1746): CodeIgniter\Database\BaseConnection->query('Select id from ...')
#2 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Model.php(796): CodeIgniter\BaseModel->__call('query', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/app/Views/LandingPage/index.php(144): CodeIgniter\Model->__call('query', Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/View/View.php(230): include('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/View/View.php(232): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Common.php(1271): CodeIgniter\View\View->render('LandingPage/ind...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/app/Controllers/LandingPage.php(16): view('LandingPage/ind...')
#8 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(928): App\Controllers\LandingPage->index()
#9 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LandingPage))
#10 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/public/index.php(37): CodeIgniter\CodeIgniter->run()
#12 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#13 {main}
ERROR - 2021-12-13 02:38:47 --> Email: sendWithSmtp throwed fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Operation timed out)
CRITICAL - 2021-12-13 02:51:13 --> Too few arguments to function App\Controllers\MyJobsEmployer::showapplicants(), 0 passed in /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php on line 928 and exactly 1 expected
#0 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(928): App\Controllers\MyJobsEmployer->showapplicants()
#1 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MyJobsEmployer))
#2 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#5 {main}
CRITICAL - 2021-12-13 02:51:59 --> Too few arguments to function App\Controllers\MyJobsEmployer::showapplicants(), 0 passed in /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php on line 928 and exactly 1 expected
#0 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(928): App\Controllers\MyJobsEmployer->showapplicants()
#1 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(436): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MyJobsEmployer))
#2 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/public/index.php(37): CodeIgniter\CodeIgniter->run()
#4 /Applications/XAMPP/xamppfiles/htdocs/futureseekerslk/system/Commands/Server/rewrite.php(45): require_once('/Applications/X...')
#5 {main}
ERROR - 2021-12-13 21:19:22 --> Email: sendWithSmtp throwed fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Operation timed out)
ERROR - 2021-12-13 21:20:17 --> Email: sendWithSmtp throwed fsockopen(): Unable to connect to tls://smtp.gmail.com:465 (Operation now in progress)
